CREATE TABLE routines (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    category VARCHAR(20) NOT NULL,
    content VARCHAR(100) NOT NULL,
    start_time TIME NOT NULL,
    end_time TIME NOT NULL,
    repeat_type VARCHAR(20) NOT NULL,
    verification_object VARCHAR(40) NOT NULL,
    effective_from DATE NOT NULL,
    deleted_at TIMESTAMP,
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NOT NULL,
    CONSTRAINT fk_routines_user FOREIGN KEY (user_id) REFERENCES users(id),
    CONSTRAINT chk_routines_category CHECK (category IN ('SKIN', 'WELL_BEING', 'HEALTH_FIT', 'DIET', 'TO_DO')),
    CONSTRAINT chk_routines_repeat_type CHECK (repeat_type IN ('DAILY', 'DAYS_OF_WEEK', 'ONCE')),
    CONSTRAINT chk_routines_time_range CHECK (start_time < end_time)
);

CREATE TABLE routine_repeat_days (
    routine_id BIGINT NOT NULL,
    day_of_week VARCHAR(3) NOT NULL,
    PRIMARY KEY (routine_id, day_of_week),
    CONSTRAINT fk_routine_repeat_days_routine FOREIGN KEY (routine_id) REFERENCES routines(id) ON DELETE CASCADE,
    CONSTRAINT chk_routine_repeat_days_day_of_week CHECK (day_of_week IN ('MON', 'TUE', 'WED', 'THU', 'FRI', 'SAT', 'SUN'))
);

CREATE TABLE photo_mission_templates (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    gesture_code VARCHAR(40) NOT NULL,
    instruction_template VARCHAR(150) NOT NULL,
    active BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMP NOT NULL
);

CREATE TABLE daily_routines (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    routine_id BIGINT NOT NULL,
    user_id BIGINT NOT NULL,
    service_date DATE NOT NULL,
    category_snapshot VARCHAR(20) NOT NULL,
    content_snapshot VARCHAR(100) NOT NULL,
    start_time_snapshot TIME NOT NULL,
    end_time_snapshot TIME NOT NULL,
    verification_object_snapshot VARCHAR(40) NOT NULL,
    mission_template_id BIGINT,
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NOT NULL,
    CONSTRAINT fk_daily_routines_routine FOREIGN KEY (routine_id) REFERENCES routines(id),
    CONSTRAINT fk_daily_routines_user FOREIGN KEY (user_id) REFERENCES users(id),
    CONSTRAINT fk_daily_routines_mission_template FOREIGN KEY (mission_template_id) REFERENCES photo_mission_templates(id) ON DELETE RESTRICT,
    CONSTRAINT uq_daily_routines_routine_service_date UNIQUE (routine_id, service_date),
    CONSTRAINT chk_daily_routines_category_snapshot CHECK (category_snapshot IN ('SKIN', 'WELL_BEING', 'HEALTH_FIT', 'DIET', 'TO_DO')),
    CONSTRAINT chk_daily_routines_time_snapshot_range CHECK (start_time_snapshot < end_time_snapshot)
);

CREATE TABLE routine_verifications (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    daily_routine_id BIGINT NOT NULL,
    verification_type VARCHAR(10) NOT NULL,
    verified_at TIMESTAMP NOT NULL,
    created_at TIMESTAMP NOT NULL,
    CONSTRAINT fk_routine_verifications_daily_routine FOREIGN KEY (daily_routine_id) REFERENCES daily_routines(id),
    CONSTRAINT uq_routine_verifications_daily_routine UNIQUE (daily_routine_id),
    CONSTRAINT chk_routine_verifications_type CHECK (verification_type IN ('PHOTO', 'CHECK'))
);

CREATE TABLE routine_point_claims (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    daily_routine_id BIGINT NOT NULL,
    amount SMALLINT NOT NULL,
    claimed_at TIMESTAMP NOT NULL,
    created_at TIMESTAMP NOT NULL,
    CONSTRAINT fk_routine_point_claims_user FOREIGN KEY (user_id) REFERENCES users(id),
    CONSTRAINT fk_routine_point_claims_daily_routine FOREIGN KEY (daily_routine_id) REFERENCES daily_routines(id),
    CONSTRAINT uq_routine_point_claims_daily_routine UNIQUE (daily_routine_id),
    CONSTRAINT chk_routine_point_claims_amount CHECK (amount IN (5, 10))
);

CREATE TABLE daily_success_records (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    service_date DATE NOT NULL,
    completed_at TIMESTAMP NOT NULL,
    created_at TIMESTAMP NOT NULL,
    CONSTRAINT fk_daily_success_records_user FOREIGN KEY (user_id) REFERENCES users(id),
    CONSTRAINT uq_daily_success_records_user_service_date UNIQUE (user_id, service_date)
);
