CREATE TABLE items (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(50) NOT NULL,
    item_type VARCHAR(30) NOT NULL,
    asset_key VARCHAR(255) NOT NULL,
    active BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMP NOT NULL
);

CREATE TABLE user_items (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    item_id BIGINT NOT NULL,
    equipped BOOLEAN NOT NULL DEFAULT FALSE,
    acquired_at TIMESTAMP NOT NULL,
    CONSTRAINT fk_user_items_user FOREIGN KEY (user_id) REFERENCES users(id),
    CONSTRAINT fk_user_items_item FOREIGN KEY (item_id) REFERENCES items(id),
    CONSTRAINT uq_user_items_user_item UNIQUE (user_id, item_id)
);

CREATE TABLE item_unlock_records (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    required_points INT NOT NULL,
    item_id BIGINT,
    processed_at TIMESTAMP NOT NULL,
    CONSTRAINT fk_item_unlock_records_user FOREIGN KEY (user_id) REFERENCES users(id),
    CONSTRAINT fk_item_unlock_records_item FOREIGN KEY (item_id) REFERENCES items(id),
    CONSTRAINT uq_item_unlock_records_user_required_points UNIQUE (user_id, required_points),
    CONSTRAINT chk_item_unlock_records_required_points CHECK (required_points > 0)
);

CREATE TABLE story_episodes (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    episode_number INT NOT NULL,
    required_streak INT NOT NULL,
    avatar_stage SMALLINT NOT NULL,
    active BOOLEAN NOT NULL DEFAULT TRUE,
    CONSTRAINT uq_story_episodes_episode_number UNIQUE (episode_number),
    CONSTRAINT chk_story_episodes_required_streak CHECK (required_streak > 0),
    CONSTRAINT chk_story_episodes_avatar_stage CHECK (avatar_stage BETWEEN 2 AND 3)
);

CREATE INDEX idx_story_episodes_required_streak
    ON story_episodes(required_streak);

CREATE TABLE user_story_unlocks (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    episode_id BIGINT NOT NULL,
    unlocked_at TIMESTAMP NOT NULL,
    CONSTRAINT fk_user_story_unlocks_user FOREIGN KEY (user_id) REFERENCES users(id),
    CONSTRAINT fk_user_story_unlocks_episode FOREIGN KEY (episode_id) REFERENCES story_episodes(id),
    CONSTRAINT uq_user_story_unlocks_user_episode UNIQUE (user_id, episode_id)
);
