CREATE TABLE speech_style_profiles (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    source_type VARCHAR(20) NOT NULL,
    preset_code VARCHAR(40),
    speech_level VARCHAR(20) NOT NULL,
    sentence_length VARCHAR(20) NOT NULL,
    directness VARCHAR(10) NOT NULL,
    warmth VARCHAR(10) NOT NULL,
    playfulness VARCHAR(10) NOT NULL,
    emotional_intensity VARCHAR(10) NOT NULL,
    style_json JSONB NOT NULL,
    profanity_detected BOOLEAN NOT NULL DEFAULT FALSE,
    profanity_enabled BOOLEAN NOT NULL DEFAULT FALSE,
    valid_message_count INT,
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NOT NULL,
    CONSTRAINT fk_speech_style_profiles_user FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE,
    CONSTRAINT uq_speech_style_profiles_user UNIQUE (user_id),
    CONSTRAINT chk_speech_style_profiles_source_type CHECK (source_type IN ('KAKAO_CHAT', 'PRESET')),
    CONSTRAINT chk_speech_style_profiles_preset_code CHECK (
        (source_type = 'PRESET' AND preset_code IS NOT NULL)
        OR (source_type = 'KAKAO_CHAT' AND preset_code IS NULL)
    ),
    CONSTRAINT chk_speech_style_profiles_speech_level CHECK (speech_level IN ('BANMAL', 'JONDAEMAL')),
    CONSTRAINT chk_speech_style_profiles_sentence_length CHECK (sentence_length IN ('SHORT', 'MEDIUM', 'LONG')),
    CONSTRAINT chk_speech_style_profiles_directness CHECK (directness IN ('LOW', 'MEDIUM', 'HIGH')),
    CONSTRAINT chk_speech_style_profiles_warmth CHECK (warmth IN ('LOW', 'MEDIUM', 'HIGH')),
    CONSTRAINT chk_speech_style_profiles_playfulness CHECK (playfulness IN ('LOW', 'MEDIUM', 'HIGH')),
    CONSTRAINT chk_speech_style_profiles_emotional_intensity CHECK (emotional_intensity IN ('LOW', 'MEDIUM', 'HIGH')),
    CONSTRAINT chk_speech_style_profiles_profanity_enabled CHECK (
        profanity_enabled = FALSE OR profanity_detected = TRUE
    ),
    CONSTRAINT chk_speech_style_profiles_valid_message_count CHECK (
        valid_message_count IS NULL OR valid_message_count >= 0
    )
);

CREATE TABLE speech_style_examples (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    profile_id BIGINT NOT NULL,
    category VARCHAR(30) NOT NULL,
    source_type VARCHAR(20) NOT NULL,
    content VARCHAR(50) NOT NULL,
    created_at TIMESTAMP NOT NULL,
    CONSTRAINT fk_speech_style_examples_profile FOREIGN KEY (profile_id) REFERENCES speech_style_profiles(id) ON DELETE CASCADE,
    CONSTRAINT chk_speech_style_examples_category CHECK (
        category IN ('QUESTION', 'AGREEMENT', 'DISAGREEMENT', 'ENCOURAGEMENT', 'REACTION', 'GENERAL')
    ),
    CONSTRAINT chk_speech_style_examples_source_type CHECK (source_type IN ('USER_MESSAGE', 'AI_GENERATED'))
);

CREATE INDEX idx_speech_style_examples_profile_category
    ON speech_style_examples(profile_id, category);

CREATE TABLE avatar_dialogues (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    profile_id BIGINT NOT NULL,
    situation VARCHAR(40) NOT NULL,
    content VARCHAR(50) NOT NULL,
    contains_user_name BOOLEAN NOT NULL DEFAULT FALSE,
    contains_profanity BOOLEAN NOT NULL DEFAULT FALSE,
    last_used_at TIMESTAMP,
    use_count INT NOT NULL DEFAULT 0,
    created_at TIMESTAMP NOT NULL,
    CONSTRAINT fk_avatar_dialogues_profile FOREIGN KEY (profile_id) REFERENCES speech_style_profiles(id) ON DELETE CASCADE,
    CONSTRAINT chk_avatar_dialogues_situation CHECK (
        situation IN (
            'ROUTINE_UPCOMING',
            'ROUTINE_AVAILABLE',
            'ROUTINE_REMINDER',
            'ROUTINE_COMPLETED',
            'ALL_COMPLETED',
            'STREAK_CONTINUED',
            'STREAK_BROKEN',
            'RETURN_AFTER_ABSENCE'
        )
    ),
    CONSTRAINT chk_avatar_dialogues_use_count CHECK (use_count >= 0)
);

CREATE INDEX idx_avatar_dialogues_profile_situation
    ON avatar_dialogues(profile_id, situation);

CREATE TABLE speech_analysis_jobs (
    id UUID PRIMARY KEY,
    user_id BIGINT NOT NULL,
    status VARCHAR(50) NOT NULL,
    expires_at TIMESTAMP NOT NULL,
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NOT NULL,
    CONSTRAINT fk_speech_analysis_jobs_user FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE,
    CONSTRAINT chk_speech_analysis_jobs_status CHECK (
        status IN (
            'UPLOADED',
            'WAITING_PARTICIPANT_SELECTION',
            'PREPROCESSING',
            'ANALYZING',
            'GENERATING_DIALOGUES',
            'COMPLETED',
            'FAILED',
            'EXPIRED'
        )
    )
);

CREATE INDEX idx_speech_analysis_jobs_user_created_at
    ON speech_analysis_jobs(user_id, created_at);

CREATE INDEX idx_speech_analysis_jobs_status_expires_at
    ON speech_analysis_jobs(status, expires_at);
